FROM docker.io/oven/bun:1.3.0-alpine AS build
WORKDIR /app
COPY package.json bun.lock bunfig.toml ./
RUN bun install --frozen-lockfile
COPY public ./public
COPY src ./src
RUN bun run build

FROM docker.io/oven/bun:1.3.0-alpine
WORKDIR /app
COPY --from=build --chown=bun:bun /app/package.json /app/bun.lock /app/bunfig.toml ./
COPY --from=build --chown=bun:bun /app/node_modules ./node_modules
COPY --from=build --chown=bun:bun /app/public ./public
COPY --from=build --chown=bun:bun /app/src ./src
COPY --from=build --chown=bun:bun /app/dist ./dist
USER bun
EXPOSE 3000
CMD ["bun", "run", "start"]
